uc-cdis/gen3-gitops

- LICENSE.txt
- NOTICE.txt
Link to JIRA ticket if there is one: [
](https://ctds-planx.atlassian.net/browse/ISO-4129)
Added the license and notice docs needed to make the repo public.
> Documents needed to turn repo public

- bihprod/bih-staging.data-commons.org/values/values.yaml
updating sheepdog and FEFW
Updated versions for services (sheepdog + FEFW)
> Update values.yaml for BIH staging

- .github/workflows/integration_tests.yaml
> Add integration test workflow

- brhprod/brhstaging.data-commons.org/values/values.yaml
> BRH staging changes

- .secrets.baseline
- bdcat-stagingdatastage/staging.gen3.biodatacatalyst.nhlbi.nih.gov/values/values.yaml
- bdcatprod/preprod.gen3.biodatacatalyst.nhlbi.nih.gov/values/values.yaml
- brhprod/brh.data-commons.org/values/values.yaml
- dcf-staging/nci-crdc-staging.datacommons.io/values/values.yaml
- dcfprod/nci-crdc.datacommons.io/values/values.yaml
- icgc/icgc.bionimbus.org/values/values.yaml
- midrcvalidate/validate.midrc.org/values/values.yaml
- pdp-commons/mc2dp.data-commons.org/values/values.yaml
> Added fence service accounts

- bdcatprod/preprod.gen3.biodatacatalyst.nhlbi.nih.gov/values/values.yaml
> Fixing usersync name

- .secrets.baseline
- bdcat-stagingdatastage/staging.gen3.biodatacatalyst.nhlbi.nih.gov/values/values.yaml
- bdcatprod/preprod.gen3.biodatacatalyst.nhlbi.nih.gov/values/values.yaml
> Update FENCE_CONFIG_PUBLIC for bdcat non-prod envs

- .secrets.baseline
- bdcatprod/preprod.gen3.biodatacatalyst.nhlbi.nih.gov/values/values.yaml
> Update values structure for bdcat-internalstaging etlMapping

- pdp-commons/mc2dp.data-commons.org/values/values.yaml
> Sync qa-prom aggMDS to prod

- healprod/externaldata.healdata.org/values/values.yaml
- healprod/healdata.org/values/values.yaml
> Cutover HEALPROD and HEALEXTERNAL to prod load balancer

- healprod/healdata.org/values/values.yaml
- healprod/preprod.healdata.org/values/values.yaml
- update batch export job in heal preprod and prod
> update batch export job

- .secrets.baseline
- vadcprod/vpodc.data-commons.org/values/values.yaml
> Update ingress group for vadcprod

- bdcatprod/gen3.biodatacatalyst.nhlbi.nih.gov/values/values.yaml
> Fix name of secret for peregrine database credentials

- bdcatprod/gen3.biodatacatalyst.nhlbi.nih.gov/values/values.yaml
> add release 39 buckets helm

- pdp-commons/mc2dp.data-commons.org/values/values.yaml
Update of mc2dp agg mds config
> mc2dp update aggMDS config

- pdp-commons/mc2dp.data-commons.org/values/values.yaml
- added `entity_type` field to subject and studies
Changed URL for Windber to Prod and changed its website
> changes for aggmds to change windber url and add entiity type field

- pdp-commons/mc2dp.data-commons.org/values/values.yaml
> lower jupyter cpu/memory in mc2dp

- healprod/healdata.org/values/values.yaml
- healprod/preprod.healdata.org/values/values.yaml
- deploy noew landing page with updated datasets information to HEAL preprod and prod
> deploy new datasets to heal

- chordsprod/chordshealth.org/values/values.yaml
- chordsprod/staging.chordshealth.org/values/values.yaml
- unfunded/caninedc.org/values/values.yaml
- unfunded/gen3.datacommons.io/values/values.yaml
> Guppy fixes

- pdp-commons/mc2dp.data-commons.org/values/values.yaml
> mc2dp updates from qa

- bdcatprod/preprod.gen3.biodatacatalyst.nhlbi.nih.gov/values/values.yaml
Bump dictionary to 4.6.5
Link to JIRA ticket if there is one: https://ctds-planx.atlassian.net/browse/BDC-685
> Update PreProd BDC DD in values.yaml

- pdp-commons/mc2dp.data-commons.org/values/values.yaml
Commons value not showing for windber
> changes for Mc2dp windber values

- pdp-commons/mc2dp.data-commons.org/values/values.yaml
> latest qa aggMDS config

- midrcprod/data.midrc.org/values/values.yaml
- midrcprod/staging.midrc.org/values/values.yaml
upping the "targetCPUUtilizationPercentage" so we can lower the amount of replicas deployed.
> Upping "targetCPUUtilizationPercentage"

- dcfprod/nci-crdc.datacommons.io/values/values.yaml
> Disable indexd metrics scarping

- qaplanetv1/cluster-values/cluster-values.yaml
> Enable crossplane in qaplanetv1

- .secrets.baseline
- midrcprod/data.midrc.org/values/values.yaml
Link to JIRA ticket if there is one: [MIDRC-1113](https://ctds-planx.atlassian.net/browse/MIDRC-1113)
* Fix incorrect YAML format in hatchery config for midrcprod values.yaml
* Update tag for hatchery container image from `master` to `2.0.1` tag in midrcprod values.yaml
[MIDRC-1113]: https://ctds-planx.atlassian.net/browse/MIDRC-1113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update the jupyter image for MIDRC prod hatchery image, also fix yaml config

- healprod/healdata.org/values/values.yaml
> set data upload bucket for heal

- ci/default/values/etl.yaml
- ci/default/values/values.yaml
> Update Dictionary and ETL Mapping for CI Default

- dcfprod/nci-crdc.datacommons.io/values/values.yaml
update memory limit dcfprod indexd
> update memory limit dcfprod indexd

- .secrets.baseline
- bdcat-stagingdatastage/staging.gen3.biodatacatalyst.nhlbi.nih.gov/values/values.yaml
- bdcatprod/gen3.biodatacatalyst.nhlbi.nih.gov/values/values.yaml
- bdcatprod/preprod.gen3.biodatacatalyst.nhlbi.nih.gov/values/values.yaml
- bihprod/imaging-hub.data-commons.org/values/values.yaml
- bloodv2/data.bloodpac.org/values/values.yaml
- brhprod/brh.data-commons.org/values/values.yaml
- brhprod/brhstaging.data-commons.org/values/values.yaml
- covid19prod/chicagoland.pandemicresponsecommons.org/values/values.yaml
- dcfprod/nci-crdc.datacommons.io/values/values.yaml
- healprod/externaldata.healdata.org/values/values.yaml
- healprod/healdata.org/values/values.yaml
- healprod/preprod.healdata.org/values/values.yaml
- jcoinprod/jcoin.datacommons.io/values/values.yaml
- kidsfirst-kfqa2/gen3qa.kidsfirstdrc.org/values/values.yaml
- kidsfirst-prodv1/data.kidsfirstdrc.org/values/values.yaml
- kidsfirst-skfqa/gen3staging.kidsfirstdrc.org/values/values.yaml
- midrcprod/data.midrc.org/values/values.yaml
- midrcprod/staging.midrc.org/values/values.yaml
- midrcvalidate/validate.midrc.org/values/values.yaml
- midrcvalidate/validatestaging.midrc.org/values/values.yaml
- pdp-commons/mc2dp.data-commons.org/values/values.yaml
- vadcprod/vpodc.data-commons.org/values/values.yaml
updating envs to have pdb set and fixing some environments to use replicaCount value instead of replicas
> Set PDB to "true" for envs

- devplanetv2/cluster-values/cluster-values.yaml
> Add crossplane to devplanetv2

- chordsprod/staging.chordshealth.org/values/etl.yaml
> Bump tube to 2025.07 in chords staging

- bdcatprod/gen3.biodatacatalyst.nhlbi.nih.gov/values/values.yaml
> fix(fence): bump

- vadcprod/vpodc.data-commons.org/values/values.yaml
> Add frontend-framework to vpodc

- bdcatprod/preprod.gen3.biodatacatalyst.nhlbi.nih.gov/values/values.yaml
https://ctds-planx.atlassian.net/browse/GPE-1790
add release 40 buckets
> preprod buckets release 40

- bdcatprod/gen3.biodatacatalyst.nhlbi.nih.gov/values/values.yaml
Link to JIRA ticket if there is one: https://ctds-planx.atlassian.net/browse/GPE-1790
update BDC dd to 4.6.5
> update BDC Prod dd

- midrcprod/staging.midrc.org/values/values.yaml
> updating midrc-staging dd to version 1.4.0

- chordsprod/staging.chordshealth.org/values/values.yaml
> Set tierAccessLevel to regular in chords staging

- chordsprod/staging.chordshealth.org/values/values.yaml
> Set guppy to libre in chords staging

- chordsprod/staging.chordshealth.org/values/values.yaml
fixed link property to key_data_resources in supplementary_file node in dd v1.5.4.
https://github.com/uc-cdis/chords-health-dictionary/releases/tag/1.5.4
> updated data model to v1.5.4

- dcfprod/nci-crdc.datacommons.io/values/values.yaml
[DCF-2210](https://ctds-planx.atlassian.net/browse/DCF-2210)
[DCF-2215](https://ctds-planx.atlassian.net/browse/DCF-2215)
[DCF-2208](https://ctds-planx.atlassian.net/browse/DCF-2208)
[DCF-2214](https://ctds-planx.atlassian.net/browse/DCF-2214)
[DCF-2217](https://ctds-planx.atlassian.net/browse/DCF-2217)
[DCF-2216](https://ctds-planx.atlassian.net/browse/DCF-2216)
[DCF-2209](https://ctds-planx.atlassian.net/browse/DCF-2209)
[DCF-2211](https://ctds-planx.atlassian.net/browse/DCF-2211)
[DCF-2218](https://ctds-planx.atlassian.net/browse/DCF-2218)
[DCF-2212](https://ctds-planx.atlassian.net/browse/DCF-2212)
[DCF-2210]: https://ctds-planx.atlassian.net/browse/DCF-2210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DCF-2215]: …
> Add KF Buckets to Production

- covid19prod/chicagoland.pandemicresponsecommons.org/values/values.yaml
> Update audit version in covid19

- CODEOWNERS
> Add CODEOWNERS to gen3-gitops

- brhprod/brh.data-commons.org/values/values.yaml
- brhprod/brhstaging.data-commons.org/values/values.yaml
> Set user id to 1010 in the new tutorial image

- devplanetv2/cluster-values/cluster-values.yaml
- devplanetv2/cluster-values/custom-objects/namespace-whitelist.yaml
- devplanetv2/cluster-values/custom-objects/shutdown-cronjob.yaml
- qaplanetv1/cluster-values/cluster-values.yaml
- qaplanetv1/cluster-values/custom-objects/namespace-whitelist.yaml
- qaplanetv1/cluster-values/custom-objects/shutdown-cronjob.yaml
> Configure custom-objects for qaplanetv1

- covid19prod/chicagoland.pandemicresponsecommons.org/values/values.yaml
> Add PRC jupyter notebook

- healprod/externaldata.healdata.org/values/values.yaml
Gen3 Monthly Release 2025.09  1756825822
> Gen3 Monthly Release 2025.09  1756825822

- chordsprod/chordshealth.org/values/etl.yaml
> Update etl.yaml for chordsprod

- unfunded/aids.diseasedatahub.org/values/portal.yaml
- unfunded/diseasedatahub.org/values/portal.yaml
- unfunded/flu.diseasedatahub.org/values/portal.yaml
- unfunded/gen3.datacommons.io/values/portal.yaml
- unfunded/microbiome.diseasedatahub.org/values/portal.yaml
- unfunded/tb.diseasedatahub.org/values/portal.yaml
> Reduce cpu requests in unfunded

- bdcatprod/preprod.gen3.biodatacatalyst.nhlbi.nih.gov/values/values.yaml
Link to JIRA ticket if there is one: https://ctds-planx.atlassian.net/browse/GPE-1791?quickFilter=658
correcting preprod buckets BDC release 41
> correct release 41 preprod buckets

- CODEOWNERS
> Update CODEOWNERS for MIDRC from Ao, to Anthony

- brhprod/brh.data-commons.org/values/values.yaml
> Enable hot nodes in brh with 2 cpu, 4Gi per az (2 users per az, 6 ttl) 

- covid19prod/chicagoland.pandemicresponsecommons.org/values/values.yaml
> Fix covid19prod ws

- .secrets.baseline
- bdcat-stagingdatastage/staging.gen3.biodatacatalyst.nhlbi.nih.gov/values/values.yaml
- bdcatprod/preprod.gen3.biodatacatalyst.nhlbi.nih.gov/values/values.yaml
- bihprod/imaging-hub.data-commons.org/values/values.yaml
- bloodv2/data.bloodpac.org/values/values.yaml
- headneck/headneckcancerbank.data-commons.org/values/values.yaml
- healprod/healdata.org/values/values.yaml
- healprod/preprod.healdata.org/values/values.yaml
- midrcprod/data.midrc.org/values/values.yaml
- midrcprod/staging.midrc.org/values/values.yaml
- midrcvalidate/validate.midrc.org/values/values.yaml
- midrcvalidate/validatestaging.midrc.org/values/values.yaml
Adding WAF for remaining commons.
> adding webacl to remaining commons.

- .secrets.baseline
- bdcatprod/gen3.biodatacatalyst.nhlbi.nih.gov/values/values.yaml
- bdcatprod/preprod.gen3.biodatacatalyst.nhlbi.nih.gov/values/values.yaml
We made some changes to the structure of the AWS Secrets Manager Secret so we want to use our newly formatted secret.
> updating external secrets for bdcatprod and staging.

- brhprod/brhstaging.data-commons.org/values/values.yaml
add new image references for tutorial and generic images.  
new images:
- have welcome pages
- tutorial has a number of notebook changes
update labApp reference to point to welcome file
> Update BRH staging values.yaml (welcome files and notebook changes)

- jcoinprod/jcoin.datacommons.io/values/values.yaml
Update values.yaml disable mutatingwebhook - jcoinprod
> Update values.yaml disable mutatingwebhook - jcoinprod

- midrcvalidate/validate.midrc.org/values/values.yaml
> changing the validate midrc DD to version 1.4.0

- pdp-commons/mc2dp.data-commons.org/values/values.yaml
- aggmds changes
- Merged all rows in the explorer in the aggregated data
- Removed Metabolomics, VMOAT, and BLOODPAC as there was no real or mock data provided
- onboarded PNNL
- removed all individual entries for Commons as we have merged ones now
> explorer changes to prod

- midrcprod/data.midrc.org/values/values.yaml
Link to JIRA ticket if there is one:  [MIDRC-1139](https://ctds-planx.atlassian.net/browse/MIDRC-1139)
[MIDRC-1139]: https://ctds-planx.atlassian.net/browse/MIDRC-1139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update values.yaml to bump up portal in midrcprod

- bdcatprod/preprod.gen3.biodatacatalyst.nhlbi.nih.gov/values/values.yaml
- point to latest dictionary release, 4.6.7
> Update BDC PreProd dd in values.yaml

- bihprod/bih-staging.data-commons.org/values/values.yaml
- bihprod/imaging-hub.data-commons.org/values/values.yaml
- midrcprod/data.midrc.org/values/values.yaml
- midrcprod/staging.midrc.org/values/values.yaml
Link to JIRA ticket if there is one: [MIDRC-1142](https://ctds-planx.atlassian.net/browse/MIDRC-1142)
* The new MIDRC notebooks require an updated configuration in order to be used as workspaces.
[MIDRC-1142]: https://ctds-planx.atlassian.net/browse/MIDRC-1142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update hatchery config in MIDRC envs

- brhprod/brhstaging.data-commons.org/values/values.yaml
Update Generic and Tutorial images to include updates to welcome pages
> Update BRH staging workspace images

- qaplanetv1/cluster-values/cluster-values.yaml
Update cluster-values.yaml qaplanetv1 eks upgrade
> Update cluster-values.yaml qaplanetv1

- healprod/preprod.healdata.org/values/portal/gitops.json
https://ctds-planx.atlassian.net/browse/HP-2298
> Add cite button to HEAL preprod

- jcoinprod/jcoin.datacommons.io/values/values.yaml
https://ctds-planx.atlassian.net/browse/HP-2299
> Adding citation page to JCOIN

- bdcat-stagingdatastage/staging.gen3.biodatacatalyst.nhlbi.nih.gov/values/values.yaml
> BDC Staging Fence 12.1.0

- midrcprod/data.midrc.org/values/values.yaml
> Fix presigned-url fence role ARN
